# Generated by Django 3.2 on 2022-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooth', '0003_auto_20220527_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='location_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
